# Generated by Django 5.0.3 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='photo',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
