# Generated by Django 5.0.3 on 2024-03-23 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_games_liked_by_alter_games_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
