# Generated by Django 5.0.3 on 2024-03-23 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='games',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
